<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Visual merchandiser ui part by Amasty for Magento 2 (System)
 */
/**
 * Amasty VisualMerchUi widget input
 *
 */

$label = $block->getData('label');
?>

<input id="<?= $block->escapeHtml($block->getId()); ?>"
       class="admin__control-text <?= $block->escapeHtml($block->getData('class')); ?>"
       type="text"
       data-form-part="category_form"
       name="<?= $block->escapeHtml($block->getData('name')); ?>"
       placeholder="<?= $block->escapeHtml($label ? $label : ''); ?>"
/>
