<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
/** @var \Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $this->helper(\Magento\Customer\Helper\Address::class);
$requiredAttributesPrechecked = $block->getData('required_attributes_prechecked');
?>
<form class="form-address-edit" action="<?= $block->escapeUrl($block->getSaveUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>" />
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>" />
        <?= $block->getNameBlockHtml() ?>
        <?php if ($addressHelper->isAttributeVisible('telephone')) : ?>
            <div class="field telephone <?php if (in_array('telephone', $requiredAttributesPrechecked)) :
                                        ?>required<?php endif; ?>">
                <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input type="number" name="telephone" value="<?= $block->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('telephone') ?>" id="telephone" />
                </div>
            </div>
        <?php endif; ?>
        <?php if ($addressHelper->isAttributeVisible('fax')) : ?>
            <div class="field fax">
                <label class="label" for="fax"><span><?= $block->escapeHtml(__('Fax')) ?></span></label>
                <div class="control">
                    <input type="number" name="fax" id="fax" title="<?= $block->escapeHtmlAttr(__('Fax')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getFax()) ?>" class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('fax') ?>" />
                </div>
            </div>
        <?php endif; ?>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend><br>
        <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
            <div class="control">
                <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="street_1" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>" />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $addressHelper->getStreetLines(); $_i <= $_n; $_i++) : ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>" />
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($addressHelper->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span></label>
                <div class="control">
                    <input type="text" name="vat_id" value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('vat_id') ?>" id="vat_id" />
                </div>
            </div>
        <?php endif; ?>
        <div class="field region required">
            <label class="label" for="region_id"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : ''; ?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region') ?>" <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : ''; ?> />
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
            <div class="control">
                <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode') ?>" />
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
            <div class="control">
                <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city') ?>" id="city" />
            </div>
        </div>
        <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_address_user_attributes'); ?>
        <?php if ($userDefinedAttributes) : ?>
            <?= $userDefinedAttributes->setShowContainer(false)->toHtml() ?>
        <?php endif; ?>
       
        <div class="field country required">
            <div class="control" style="display: none">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>

        <?php if ($block->isDefaultBilling()) : ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("This is your default billing address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()) : ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox" />
                <label class="label" for="primary_billing"><span><?= $block->escapeHtml(__('Use as my default billing address')) ?></span></label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()) : ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("This is your default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()) : ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox" />
                <label class="label" for="primary_shipping"><span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span></label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_shipping" value="1" />
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" data-action="save-address" title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $block->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<script>
    require(['jquery'], function($) {

        var telephone = '#telephone',
            zipcode = '#zip',
            subdistrict = '#city',
            district = '#subdistrict';
        
        var selector_key_arr = [
            telephone,
            zipcode,
            subdistrict,
            district
        ];
        function regexTest(input) {
            return input !== '' && regex.test(input)
        }

        function inputValLongEngough(el) {
            var s = $(el).attr('name'),
                val = $(el).val();

            if (
                (s === 'postcode' && val.length < 3) ||
                (s === 'region' && val.length < 2) ||
                (s === 'city' && val.length < 2) ||
                (s === 'custom_attributes[subdistrict]' && val.length < 2) ||
                (s === 'subdistrict' && val.length < 2) ||
                (s === 'telephone' && val.length != 10)
            ) {
                return true;
            }
            return false;
          
        }

        function addError(s, selector_key){
            switch (s) {
                case 'telephone':
                    $("#shipping-telephone-error-phone").remove();
                    $(selector_key).after('<div class="mage-error" id="shipping-telephone-error-phone"><?= __('Please enter a valid phone number with 10 digits.') ?></div>');
                    $(selector_key).css('border','1px solid red');
                    break;
                case 'postcode':
                    $("#shipping-telephone-error-zip").remove();
                    $(selector_key).after('<div class="mage-error" id="shipping-telephone-error-zip"><?= __('Please enter a valid zip/postal code with 5 digits.') ?></div>');
                    $(selector_key).css('border','1px solid red');
                    break;
                case 'city':
                    $("#shipping-telephone-error-dic").remove();
                    $(selector_key).after('<div class="mage-error" id="shipping-telephone-error-dic"><?= __('Please enter a valid district with min 2 characters.') ?></div>');
                    $(selector_key).css('border','1px solid red');
                    break;
                case 'subdistrict':
                    $("#shipping-telephone-error-sub").remove();
                    $(selector_key).after('<div class="mage-error" id="shipping-telephone-error-sub"><?= __('Please enter a valid subdistrict with min 2 characters.') ?></div>');
                    $(selector_key).css('border','1px solid red');
                    break;
            }
        }

        function removeError(s, selector_key){
            switch (s) {
                case 'telephone':
                    $("#shipping-telephone-error-phone").remove();
                    $(selector_key).css('border','');
                    break;
                case 'postcode':
                    $("#shipping-telephone-error-zip").remove();
                    $(selector_key).css('border','');
                    break;
                case 'city':
                    $("#shipping-telephone-error-dic").remove();
                    $(selector_key).css('border','');
                    break;
                case 'subdistrict':
                    $("#shipping-telephone-error-sub").remove();
                    $(selector_key).css('border','');
                    break;
            }
        }

        $(document).ready(function() {
            jQuery.each(selector_key_arr, function (i, selector_key) {
                $(selector_key).on('keyup', function(e){
                    var s = $(selector_key).attr('name');

                    if (inputValLongEngough(selector_key)) {
                        e.preventDefault();
                        $('.action.submit.primary').attr('disabled', true);
                        if ($("#shipping-telephone-error").length > 0) {
                            $("#shipping-telephone-error").remove();
                            $(selector_key).css('border','');
                        }
                        addError(s,selector_key);
                        $('.action.submit.primary').attr('disabled',true);
                    } else {
                        removeError(s,selector_key);
                        $('.action.submit.primary').removeAttr('disabled');
                    }
                })
            });
        });
    });
</script>