<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Grouped Options for Magento 2
 */ /** @var \Amasty\GroupedOptions\Block\Adminhtml\Group\Edit\After $block */?>
<script>
    require([
        'Amasty_GroupedOptions/js/group-visual'
    ], function(Visual) {
        Visual(<?= /* @noEscape */ $block->getJsonVisualConfig() ?>);
    });
</script>
