<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

$isFreeProduct = ((float) $product->getPrice() < 1) ? true : false ;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockManager = $objectManager->get('\Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($product->getId());
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()) :?>
        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else :?>
            <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
        </a>
    <?php else :?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-brand">
                <span><?php echo $_item->getProduct()->getAttributeText('brand') ?></span>
            </strong>
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) :?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else :?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()) :?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) :?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <!-- <dt><?= $block->escapeHtml($_option['label']) ?></dt> -->
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                            <?php else :?>
                                <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()) :?>
                <?php foreach ($messages as $message) :?>
                    <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <div class="field qty">
            <div class="control qty" data-bind="scope: 'qty_change'">
                <div class="btn-group-control-qty">
                    <button class="btn-update-qty decrease-qty" style="display: <?=(!$isFreeProduct) ?  'inline-block' :  'none'?>" >-</button>
                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                           name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                           data-cart-id="<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                           data-max-sale-qty="<?php /* @escapeNotVerified */ echo $stockManager->getMaxSaleQty() ; ?>"
                           data-min-sale-qty="<?php /* @escapeNotVerified */ echo $stockManager->getMinSaleQty() ; ?>"
                           value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                           type="number"
                           size="4"
                           step="any"
                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"
                           readonly
                    />
                    <button class="btn-update-qty increase-qty" style="display: <?=(!$isFreeProduct) ?  'inline-block' :  'none'?>" >+</button>
                </div>
            </div>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) :?>
            <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
    <td>
        
    <div class="actions-toolbar">
            <?= /* @noEscape */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>

</tbody>
