<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage */

// Get all visible items in cart
$quote = $block->getData("view_model")->getQuoteData();

$products = [];

foreach($quote->getAllVisibleItems() as $_item) {

    $_categoryNameArray = [];
    foreach($_item->getProduct()->getCategoryCollection()->addAttributeToSelect('name') as $category){
        $_categoryNameArray[] = $category->getName(); 
    }
    $_category = join('/', $_categoryNameArray);

    $simpleProductOption = $_item->getOptionByCode('simple_product');
    if($simpleProductOption){
        $color = $simpleProductOption->getProduct()->getAttributeText('color');
        $size = $simpleProductOption->getProduct()->getAttributeText('size');
    }

    $product = (object) [
        'id' => $_item->getSku(),
        'name' => $_item->getName(),
        'price' => $_item->getProduct()->getFinalPrice(),
        'category' => $_category,
        'brand' => $_item->getProduct()->getAttributeText('brand'),
        'variant' => isset($color) ? $color : $_item->getProduct()->getAttributeText('color'),
        'dimension1' => (isset($size) && $size != "") ? $size : $_item->getProduct()->getAttributeText('size'),
        'quantity' => $_item->getQty(),
    ];

    if($product->dimension1 == null){
        $product->dimension1 = "";
    }

    if($product->variant == null){
        $product->variant = "";
    }

    $products[] = $product;
}



?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>");
            return url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
        })
    </script>
</div>

<script>
    require([
            'jquery'
        ], function ($) {
            $(document).ready(function(){

                var checkoutStep = location.hash;
                if(checkoutStep == "#payment" || checkoutStep == "#shipping"){
                    window.dataLayer = window.dataLayer || [];
                    let productsInCart = <?php echo json_encode($products); ?>;
                    var i,j,productsInCartChunk,chunk = 12;
                    for (i=0,j=productsInCart.length; i<j; i+=chunk) {
                        productsInCartChunk = productsInCart.slice(i,i+chunk);
                        dataLayer.push({
                            'event': 'checkout-ftd',
                            'currencyCode': 'THB',
                            'basketTotal':  '<?php echo $quote->getGrandTotal() ?>',
                            'ecommerce': {
                                'checkout': {
                                    'actionField' : {'step' : checkoutStep == "#shipping" ? '1' : '2'},
                                    'products': productsInCartChunk
                                }   
                            }
                        });
                    }
                }
            });
        });
    
        window.onhashchange = function(){
            
            var checkoutStep = location.hash;
            if(checkoutStep == "#payment" || checkoutStep == "#shipping"){
                window.dataLayer = window.dataLayer || [];
                let productsInCart = <?php echo json_encode($products); ?>;
                var i,j,productsInCartChunk,chunk = 12;
                for (i=0,j=productsInCart.length; i<j; i+=chunk) {
                    productsInCartChunk = productsInCart.slice(i,i+chunk);
                    dataLayer.push({
                        'event': 'checkout-ftd',
                        'currencyCode': 'THB',
                        'basketTotal':  '<?php echo $quote->getGrandTotal() ?>',
                        'ecommerce': {
                            'checkout': {
                                'actionField' : {'step' : checkoutStep == "#payment" ? '2' : '1'},
                                'products': productsInCartChunk
                            }   
                        }
                    });
                }
            }
        };
</script>