stage:
  global:
    SCD_ON_DEMAND: true
    SKIP_HTML_MINIFICATION: true
  build:
    SKIP_SCD: false
    SCD_STRATEGY: "compact"
    QUALITY_PATCHES:
      - MDVA-12304
      - MDVA-15546
      - MDVA-30106
      - ACSD-48417
      - ACSD-50817
      - ACSD-48070
      - ACSD-53347
      - ACSD-51265
      - ACSD-53728
      - ACSD-52929
      - ACSD-53583
      - ACSD-54890
      - ACSD-48212
      - ACSD-48059
      - ACSD-48164
      - ACSD-49370
      - ACSD-48784
      - ACSD-48857
      - ACSD-50116
      - ACSD-50858
      - ACSD-51102
      - ACSD-51431
      - ACSD-51857

  deploy:
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 20000
      consumers: []
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    MYSQL_USE_SLAVE_CONNECTION: true
    DATABASE_CONFIGURATION:
      _merge: true
      slave_connection:
        default:
          synchronous_replication: false
