<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Social Login Base for Magento 2
*/
?>
<?php
/** @var \Amasty\SocialLogin\Block\Account\SocialAccounts $block */
/** @var \Magento\Framework\Escaper $escaper */

$socialButtonsType = $block->getButtonShapeClass();
$linked = $block->getLinkedAccountsData();
$enabledLabels = $block->getButtonLabelState();
?>

<div class="amsl-accounts">
    <?php if ($linked): ?>
        <div class="amsl-accounts-block">
            <legend class="legend">
                <span><?= $escaper->escapeHtml(__('Linked accounts')); ?></span>
            </legend>
            <div class="amsl-linked-wrapper <?= $escaper->escapeHtmlAttr($block->getButtonShapeClass()); ?>">
                <?php foreach ($block->getLinkedAccountsData() as $key => $data): ?>
                    <div class="amsl-linked -<?= $escaper->escapeHtmlAttr($socialButtonsType); ?>">
                        <span class="amsl-button -<?= $escaper->escapeHtml($data['type']); ?>">
                            <span class="amsl-social-icon"></span>
                        </span>
                        <div class="amsl-name"><?= $escaper->escapeHtml($data['name']); ?></div>
                        <a class="amsl-unlink"
                           title="<?= $escaper->escapeHtmlAttr(__('Unlink')); ?>"
                           href="<?= $escaper->escapeUrl($data['url']); ?>">
                                <?= $escaper->escapeHtml(__('Unlink')); ?>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->getUnLinkedAccountsData()): ?>
        <div class="amsl-accounts-block">
            <legend class="legend">
                <span><?= $escaper->escapeHtml(__('Link new accounts')); ?></span>
            </legend>
            <div class="amsl-social-login">
                <div class="amsl-buttons">
                    <?php foreach ($block->getUnLinkedAccountsData() as $key => $data): ?>
                        <div class="amsl-button-wrapper
                                <?= $escaper->escapeHtmlAttr($block->getButtonShapeClass()); ?>
                                <?= $escaper->escapeHtmlAttr($enabledLabels ? 'with-label' : ''); ?>">
                            <a class="amsl-button -<?= $escaper->escapeHtml($data['type']); ?>"
                               title="<?= $escaper->escapeHtmlAttr(__('Link')); ?>"
                               href="<?= $escaper->escapeUrl($data['url']); ?>">
                                <span class="amsl-social-icon"></span>
                                <?php if ($socialButtonsType && $enabledLabels): ?>
                                    <span class="amsl-text">
                                    <?= $escaper->escapeHtml(__('Link  %1', $data['label'])); ?>
                                </span>
                                <?php endif; ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
