<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package FAQ and Product Questions for Magento 2
 */
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="amfaq-rating"
     data-bind="scope: 'faq-rating.faq-rating-item-<?= $block->escapeHtml($block->getData('questionId')); ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
