<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Social Login Base for Magento 2
*/
?>
<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Amasty\SocialLogin\ViewModel\ReportBuilder\Advertise $viewModel
 */

$viewModel = $block->getViewModel();
?>

<?php if ($viewModel->isReportBuilderDisabled()): ?>
    <section class="amsl-suggestion-block">
        <span class="amsl-text">
            <?= /* @noEscape */ __('Try') ?> <b><?= /* @noEscape */ __('Custom Reports Builder') ?></b>
        </span>
        <a class="amsl-link abs-action-primary abs-action-l"
           title="<?= /* @noEscape */ __('Explore') ?>"
           href="<?= $escaper->escapeUrl($viewModel->getAdvUrl()) ?>">
            <?= /* @noEscape */ __('Explore') ?>
        </a>
    </section>
<?php endif; ?>
