<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Improved Layered Navigation Base for Magento 2
 */
/** @var \Amasty\Shopby\Block\Navigation\JsInit $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div data-am-js="js-init">
    <script type="text/x-magento-init">
        {
            "[data-am-js='filter-item-default']": {
                "amShopbyFilterItemDefault": {
                    "collectFilters": <?= /* @noEscape */ $block->collectFilters() ?>,
                    "clearUrl": "<?= $escaper->escapeUrl($block->getClearUrl()) ?>"
                }
            },
            "*": {
                "amShopbyResponsive": {}
            }
        }
    </script>

    <?php if ($block->getEnableStickySidebarDesktop()): ?>
        <script type="text/x-magento-init">
        {
            ".sidebar.sidebar-main": {
                "amShopbyStickySidebar": {}
            }
        }
        </script>
    <?php endif; ?>
</div>
