<?php
// @codingStandardsIgnoreFile
?>

<?php $attributeId = $block->getAttributeId()?>
<?php $isMulti = $block->getIsMultiselect()?>
<?php $canShowQty = (is_null($block->getShowQty())) ? $this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer() : $block->getShowQty();?>
<?php $canShowInstantSearch = $block->canShowInstantSearch() ? 'desktop' : ''?>
<?php $canShowInstantSearchMobile = $block->canShowInstantSearchMobile() ? 'mobile' : ''?>
<?php $categoryParamLabel = $block->getCategoryParamLabel()?>
<?php $ratingParamLabel = $block->getRatingParamLabel()?>

<?php
$listItemStyle = 'display: none';
if ($attributeId == \WeltPixel\LayeredNavigation\Helper\Data::RATING_PARAM_LABEL) {
    $listItemStyle = '';
}

?>

<div class="wp-instant-search-wrapper <?=$canShowInstantSearchMobile?> <?=$canShowInstantSearch?>">
    <input type="text" class="wp-instant-search-inp" id="instant_search_<?= /* @escapeNotVerified */ $attributeId?>" data-attr-id="<?= /* @escapeNotVerified */ $attributeId ?>" placeholder="<?= __('Search for options ...')?>">
</div>


<ol class="items" id="<?= $attributeId ?>_items" >
    <?php foreach ($filterItems as $filterItem): ?>
    <?php $requestVar = $filterItem->getFilter()->getRequestVar();?>
    <?php $filterItemVal = is_array($filterItem->getValue()) ? implode('-', $filterItem->getValue()) : $filterItem->getValue()?>
    <?php $idAddOn = $attributeId?>
    <?php if($requestVar == $categoryParamLabel):?>
        <?php $dataOptPath = $categoryParamLabel.'='.$filterItemVal;?>
    <?php elseif($requestVar == $ratingParamLabel):?>
        <?php $dataOptPath = $ratingParamLabel.'='.$filterItemVal;?>
        <?php $idAddOn = $ratingParamLabel?>
    <?php else:?>
        <?php $dataOptPath = $filterItem->getFilter()->getAttributeModel()->getAttributeCode().'='. $filterItemVal;?>
    <?php endif;?>
        <li class="item"  style="<?= $listItemStyle ?>" id="wp_ln_attr_<?= $idAddOn ?>_<?= /* @escapeNotVerified */ is_array($filterItem->getValue()) ? implode('-', $filterItem->getValue()) : $filterItem->getValue() ?>">
            <?php if ($filterItem->getCount() > 0): $filter = $filterItem->getFilter();?>
                <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                   data-opt-path="<?= /* @escapeNotVerified */ $block->escapeHtmlAttr($dataOptPath) ?>"
                    data-is-multi="<?= $isMulti?>">
                    <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                    <?php if ($canShowQty): ?>
                        <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?= /* @escapeNotVerified */ __('item') ?><?php else:?> <?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <a href="#" class="wp-filter-disabled" disabled="disabled"><?= /* @escapeNotVerified */ $filterItem->getLabel() ?></a>
                <?php if ($canShowQty): ?>
                    <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?= /* @escapeNotVerified */ __('item') ?><?php else:?><?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
    <?php if($requestVar != $ratingParamLabel):?>
        <div class="wp-ln-actions" data-visibleItems="<?= $block->getVisibleItems()?>" data-visibleItemsStep="<?= $block->getVisibleItemsStep()?>" data-attrId="<?= $attributeId?>">
            <b id="showLess_<?=$attributeId?>"  class="wp-ln-action wp-ln-show-less icon-line-arrow-up"></b>
            <b id="loadMore_<?=$attributeId?>" class="wp-ln-action wp-ln-load-more icon-line-arrow-down"></b>
        </div>
    <?php endif;?>
</ol>
