<?php
// @codingStandardsIgnoreFile
/** @var $block \WeltPixel\GA4\Block\MetaPixel\Common */

/** @var \WeltPixel\GA4\Helper\MetaPixelTracking $metaPixelHelper */
$metaPixelHelper = $this->helper('WeltPixel\GA4\Helper\MetaPixelTracking');
?>
<?php if ($metaPixelHelper->isMetaPixelTrackingEnabled()) : ?>
    <script>
        require(['jquery', 'Magento_Customer/js/customer-data'],
            function ($, customerData) {
                $( document ).ajaxComplete(function( event, xhr, settings ) {
                    if (settings.url.search('/customer\/section\/load/') > 0) {
                        var response = xhr.responseJSON;
                        if (response.wp_ga4) {
                            var metaPixel = $.parseJSON(response.wp_ga4.metapixel);
                            for (index in metaPixel) {
                                fbq(metaPixel[index].track, metaPixel[index].eventName, metaPixel[index].eventData);
                            }
                        }
                    }
                });
            });
    </script>
<?php endif; ?>
