<?php
/**
 * Product list toolbar
 *
* @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

$_helper = $this->helper('WeltPixel\AdvanceCategorySorting\Helper\Data');
$groupSettings = $_helper->getConfigValuesByGroup('general');
$displaySortByDesktop = '';
$displaySortByMobile = '';
if ($groupSettings['enable'] === '1') {
    $displaySortByDesktop = ($_helper->isSortByEnabledOnDesktop() == '1' ? 'sort-by-desktop' : 'sort-by-desktop-disabled');
    $displaySortByMobile = ($_helper->isSortByEnabledOnMobile() == '1' ? 'sort-by-mobile' : 'sort-by-mobile-disabled');
}
?>
<div class="toolbar-sorter sorter">
    <!-- <label class="sorter-label <?php echo $displaySortByDesktop ?> <?php echo $displaySortByMobile ?>" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label> -->
    <select id="sorter" data-role="sorter" style="display: none;" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
            >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>

    <div class="custom-select" id="sorter-custom">
        <?php
        $selectedOptionText = '';
        foreach ($block->getAvailableOrders() as $_key => $_order) {
            if ($block->isOrderCurrent($_key)) {
                $selectedOptionText = $_order;
                break;
            }
        }
        ?>
        <div class="select-selected" data-selected="<?= $block->escapeHtml($selectedOptionText) ?>">
            <!-- <?= $block->escapeHtml($selectedOptionText) ?> -->
            <?= $block->escapeHtml(__('Sort By')) ?>
        </div>
        <div class="select-items" style="display: none;">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) : ?>
                <div class="<?= ($selectedOptionText == $_order) ? 'selected_option' : '' ?>" data-value="<?= $block->escapeHtmlAttr($_key) ?>"><?= $block->escapeHtml(__($_order)) ?></div>
            <?php endforeach; ?>
        </div>
        <div class="am-button-sortby">
            <div class="am-show-button am-btn-sortby -horizontal" style="display: block;">
                <button amshopby-apply-filter="1"
                        id="amasty_shopby_apply_filt"
                        title="<?= $escaper->escapeHtmlAttr(__('Apply Filters')) ?>"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Apply Filters')) ?>"
                        class="amsortby-button-active amshopby-button">
                    <?= $escaper->escapeHtml(__('Apply')) ?>
                </button>
                <button class="amsortby-button-clear amshopby-button clear_all_filter">
                    <a style="color: #ffffff;" href="<?= $block->getPagerUrl('') ?>"><?= $escaper->escapeHtml(__('Clear All')) ?></a>
                </button>
            </div>
        </div>
    </div>

    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            
            $(".select-selected").click(function() {
                if($(window).width() > 769){
                    var test = $('.am-button-sortby');
                    $('.select-items').append(test);
                }
                $(this).parent().toggleClass('active');
                $(this).addClass('active');
                $(".select-items").toggle();
                $(".am-button-sortby").toggleClass('active');
                $('.theme-pearl').toggleClass('filter-overflow');
                $('.toolbar.toolbar-products').addClass('active');

                if($('html').attr('lang') == 'th'){
                    $('.toolbar-sorter .custom-select .select-items').css({
                        "top": "50px"
                    })
                }
               
                if ($(".select-items").css("display") === "none") {
                    $(".select-selected").removeClass('active');
                    $('.toolbar.toolbar-products').removeClass('active');
                }
            });

            $(".select-items div").click(function() {
                var selectedOption = $(this).text();
                var value = $(this).attr('data-value');

                $('.amsortby-button-active').click(function(){
                    $(".select-items").hide();
                    $('.select-selected').removeClass('active');
                    $('.toolbar.toolbar-products').removeClass('active');
                    $(".am-button-sortby").removeClass('active');
                    $("#sorter").val(value).change();
                    $('.theme-pearl').removeClass('filter-overflow');
                });

            });

            $(document).click(function(event) {
                if (!$(event.target).closest("#sorter-custom").length) {
                    $(".select-items").hide();
                    $('.select-selected').removeClass('active');
                    $(".am-button-sortby").removeClass('active');
                    $('.toolbar.toolbar-products').removeClass('active');
                }
            });
        });
    });
</script>