<?php
$customer = $block->getCustomer();
$back_url = $block->getBackUrl();
$markup = '';
if ($customer) {
    $queryParams = [
        '_query' => [
            'id' => $customer->getId(),
            'key' => $customer->getConfirmation(),
            'back_url' => $back_url
        ],
        '_nosid' => 1
    ];
    $markup = '<script type="application/ld+json">
                {
                  "@context": "http://schema.org",
                  "@type": "EmailMessage",
                  "potentialAction": {
                    "@type": "ViewAction",
                    "target": "' . $this->getFrontendUrl('customer/account/confirm', $queryParams) . '",
                    "name": "Confirm Email"
                  },
                  "description": "Confirm Email"
                }
            </script>';
}
?>
<?= $markup ?>