<?php
$user = $block->getUser();
$queryParams = [
    '_query' => [
        '_query_id' => $user->getId(),
        '_query_token' => $user->getRpToken()
    ],
    '_nosid' => 1
];
$markup = '';
if ($user) {
    $markup = '<script type="application/ld+json">
                {
                  "@context": "http://schema.org",
                  "@type": "EmailMessage",
                  "potentialAction": {
                    "@type": "ViewAction",
                    "target": "' . $this->getUrl('admin/auth/resetpassword', $queryParams) . '",
                    "name": "Reset Password"
                  },
                  "description": "Reset Password"
                }
            </script>';
}
?>
<?= $markup ?>