<?php
// @codingStandardsIgnoreFile

/** @var \WeltPixel\EnhancedEmail\Block\ProductsGrid $block */
?>

<?php if ($exist = ($block->getItems() && count($block->getItems()))) : ?>
    <?php
    $type = 'widget-product-grid';
    $image = 'weltpixel_enhancedemail_products_grid';
    $items = $block->getItems();
    $chunkSize = 4;
    $gridWidth = 100 / $chunkSize;
    $itemChunks = array_chunk($items, $chunkSize);
    ?>
    <table class="wp-products-grid" align="center" style="padding-bottom:5px; padding-top:40px; width: 660px">
        <tbody>
        <?php if ($block->getTitle()) : ?>
            <tr>
                <td colspan="4" align="center" style="padding-top: 10px;padding-bottom:10px;">
                    <h2 style="text-align: center; margin: 20px 0 20px 0 !important">
                        <?= $block->escapeHtml(__($block->getTitle())) ?>
                    </h2>
                </td>
            </tr>
        <?php endif ?>
        <?php foreach ($itemChunks as $itemChunk) : ?>
        <tr>
            <?php for ($i=0; $i<$chunkSize; $i++) : ?>
            <?php $_item = (isset($itemChunk[$i])) ? $itemChunk[$i] : false; ?>
            <td align="center" style="margin-left: 0px; width: <?=$gridWidth?>%">
            <?php if ($_item) : ?>
                <a style="display: inline-block; margin-bottom: 20px;" href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                    <?= $block->getImage($_item, $image)->toHtml() ?>
                </a>
                <strong style="display: inline-block; margin-bottom: 20px;">
                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                       style="font-size: 12px">
                        <?= $block->escapeHtml($_item->getName()) ?>
                    </a>
                </strong>
                <?= $block->getProductPriceHtml($_item, $type) ?>
                <?php endif; ?>
            </td>
            <?php endfor; ?>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif;?>

