<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop by Page for Magento 2 (System)
 */
/** @var $block \Amasty\ShopbyPage\Block\Adminhtml\Page\Selection */
?>
<script>
    require([
        'Amasty_ShopbyPage/js/selection'
    ], function (selection) {
        selection.init(
            '<?= $block->escapeUrl($block->getSelectionUrl()) ?>',
            '<?= $block->escapeUrl($block->getAddSelectionUrl())?>',
            '<?= $block->escapeHtml($block->getCounter())?>'
        );
        window.amastyShopbyPageSelection = selection;
    });
</script>
