<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Improved Layered Navigation Base for Magento 2
 */
/** @var \Amasty\Shopby\Block\Navigation\UrlModifier $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<?php if ($block->replaceUrl()): ?>
    <script>
        window.history.replaceState({url: '<?= $escaper->escapeUrl($block->getCurrentUrl()) ?>'},
            '',
            '<?= $escaper->escapeUrl($block->getCurrentUrl()) ?>'
        );
    </script>
<?php endif;?>
