


    td.wrapper-inner {
        background-color: <?= /* @escapeNotVerified */ $this->getBodyWrapperBackgroundColor() ?> !important;
    }

    td.header {
        background-color: <?= /* @escapeNotVerified */ $this->getHeaderBackgroundColor() ?> !important;
    }

    td.footer {
        background-color: <?= /* @escapeNotVerified */ $this->getFooterBackgroundColor() ?> !important;
    }

    td.main-content {
        background-color: <?= /* @escapeNotVerified */ $this->getBodyBackgroundColor() ?> !important;
        color: <?= /* @escapeNotVerified */ $this->getBodyFontColor() ?> !important;
    }

    tfoot.order-totals tr th, tfoot.order-totals td {
        background-color: <?= /* @escapeNotVerified */ $this->getBodyOrderTotalBackgroundColor() ?> !important;
    }

    a{
        color: <?= /* @escapeNotVerified */ $this->getBodyLinkColor() ?> !important;
        text-decoration: none;
        cursor: pointer;
    }

    * a:hover{
        color: inherit;
        text-decoration: none;
        cursor: pointer;
    }

    * a:visited{
        color: <?= /* @escapeNotVerified */ $this->getBodyLinkColor() ?> !important;
        text-decoration: none;
        cursor: pointer;
    }


    h1 {
        color: <?= /* @escapeNotVerified */ $this->getHeadingOneFontColor() ?>;
        font-family: <?= /* @escapeNotVerified */ $this->getHeadingOneFontFamily()?>, sans-serif;
        font-weight: <?= /* @escapeNotVerified */ $this->getHeadingOneFontWeight() ?>;
        font-size: <?= /* @escapeNotVerified */ $this->getHeadingOneFontSize() ?>;
        font-style: <?= /* @escapeNotVerified */ $this->getHeadingOneFontStyle() ?>;
        line-height: <?= /* @escapeNotVerified */ $this->getHeadingOneFontHeight() ?>;
    }
    h2 {
        color: <?= /* @escapeNotVerified */ $this->getHeadingTwooFontColor() ?>;
        font-family: <?= /* @escapeNotVerified */ $this->getHeadingTwooFontFamily() ?>, sans-serif;
        font-weight: <?= /* @escapeNotVerified */ $this->getHeadingTwooFontWeight() ?>;
        font-size: <?= /* @escapeNotVerified */ $this->getHeadingTwooFontSize() ?>;
        font-style: <?= /* @escapeNotVerified */ $this->getHeadingTwooFontStyle() ?>;
        line-height: <?= /* @escapeNotVerified */ $this->getHeadingTwooFontHeight() ?>;
    }
    h3 {
        color: <?= /* @escapeNotVerified */ $this->getHeadingThreeFontColor() ?>;
        font-family: <?= /* @escapeNotVerified */ $this->getHeadingThreeFontFamily() ?>, sans-serif;
        font-weight: <?= /* @escapeNotVerified */ $this->getHeadingThreeFontWeight() ?>;
        font-size: <?= /* @escapeNotVerified */ $this->getHeadingThreeFontSize() ?>;
        font-style: <?= /* @escapeNotVerified */ $this->getHeadingThreeFontStyle() ?>;
        line-height: <?= /* @escapeNotVerified */ $this->getHeadingThreeFontHeight() ?>;
    }
    p {
        color: <?= /* @escapeNotVerified */ $this->getPFontColor() ?>;
        font-family: <?= /* @escapeNotVerified */ $this->getPFontFamily() ?>, sans-serif;
        font-weight: <?= /* @escapeNotVerified */ $this->getPFontWeight() ?>;
        font-size: <?= /* @escapeNotVerified */ $this->getPFontSize() ?>;
        font-style: <?= /* @escapeNotVerified */ $this->getPFontStyle() ?>;
        line-height: <?= /* @escapeNotVerified */ $this->getPFontHeight() ?>;
    }

    button {
        color: <?= /* @escapeNotVerified */ $this->getButtonFontColor() ?>;
        background-color: <?= /* @escapeNotVerified */ $this->getButtonBgColor() ?>;
        border-color: <?= /* @escapeNotVerified */ $this->getButtonBorderColor() ?>;
        cursor: pointer;
    }

    .button .inner-wrapper td {
        background-color: <?= /* @escapeNotVerified */ $this->getButtonBgColor() ?> !important;
    }
    .button .inner-wrapper td a {
        border: 1px solid <?= /* @escapeNotVerified */ $this->getButtonBorderColor() ?> !important;
        color: <?= /* @escapeNotVerified */ $this->getButtonFontColor() ?> !important;
    }

    .button .inner-wrapper td:hover {
        background-color: <?= /* @escapeNotVerified */ $this->getButtonHoverBgColor() ?> !important;
    }

    .button .inner-wrapper td:hover a {
        border: 1px solid <?= /* @escapeNotVerified */ $this->getButtonHoverBorderColor() ?> !important;
        color: <?= /* @escapeNotVerified */ $this->getButtonHoverFontColor() ?> !important;
    }

