<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_helper = $this->helper('WeltPixel\ProductPage\Helper\Data'); ?>
<?php $selectMaxValue = $_helper->getQtySelectMaxValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = $_product->isSaleable() ? __('Add to Cart') : __('Out of Stock') ?>
<?php $addToCartClass = !$block->shouldRenderQuantity() ? 'full-width-btn' : ''; ?>

<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span>
                        <?php /* @escapeNotVerified */echo __('Qty') ?>
                    </span></label>
                <div class="control">
                    <div class="qty-container">
                        <button type="button" class="qty-plus" data-max="<?php echo $selectMaxValue; ?>"> </button>
                        <input type="text" name="qty" id="qty" class="input-text qty" value="1">
                        <button type="button" class="qty-minus"></button>
                    </div>
                </div>
            </div>

        <?php endif; ?>
        <div class="product-info-price-sticky"></div>
        <div class="actions <?php echo $addToCartClass; ?>">
            <button type="submit" title="<?php /* @escapeNotVerified */echo $buttonTitle ?>"
                class="action primary tocart" id="product-addtocart-button" <?= $_product->isSaleable() ? "" : "disabled" ?>>
                <span>
                    <?php /* @escapeNotVerified */echo $buttonTitle ?>
                </span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>

<?php if ($block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
                {
                    "#product_addtocart_form": {
                        "Magento_Catalog/product/view/validation": {
                            "radioCheckboxClosest": ".nested"
                        }
                    }
                }
            </script>
<?php else:
    $_color = "";
    $_size = "";
    $_categoryNameArray = [];

    foreach ($_product->getCategoryCollection()->addAttributeToSelect('name') as $category) {
        $_categoryNameArray[] = $category->getName();
    }
    $_category = join('/', $_categoryNameArray);

    if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
        $options = $_product->getTypeInstance()->getConfigurableOptions($_product);
        if (array_key_exists(93, $options)) {
            $_colors = $options[93];
            $_colorsArray = [];
            foreach ($_colors as $_color) {
                $_colorsArray[] = $_color["option_title"];
            }
            $_color = join('/', $_colorsArray);
        }
        if (array_key_exists(222, $options)) {
            $_sizeOptions = $options[222];
            $_sizeArray = [];
            foreach ($_sizeOptions as $_sizeOption) {
                $_sizeArray[] = $_sizeOption["option_title"];
            }
            $_size = join('/', $_sizeArray);
        }
    }

    ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            $(document).ready(function () {
                $('.qty-minus').click(function () {
                    var qtyInput = $('#qty');
                    var currentValue = parseInt(qtyInput.val(), 10);
                    if (currentValue > 1) {
                        qtyInput.val(currentValue - 1);
                    }
                });

                $('.qty-plus').click(function () {
                    var qtyInput = $('#qty');
                    var currentValue = parseInt(qtyInput.val(), 10);
                    var maxValue = parseInt($(this).data('max'), 10);
                    if (currentValue < maxValue) {
                        qtyInput.val(currentValue + 1);
                    }
                });
            });

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });

        require(['Magento_Customer/js/customer-data'], function (customerData) {

            var firstPageLoad = true;
            var cart = customerData.get('cart');
            var count;

            cart.subscribe(function () {

                if (firstPageLoad) {
                    firstPageLoad = false
                    count = cart().summary_count;
                }
                else if (cart().summary_count !== count && !firstPageLoad) {
                    let amountAdded = cart().summary_count - count;
                    count = cart().summary_count;
                    if (amountAdded > 0) {
                        let lastAddedItem = cart().items.find(i => i.product_id == cart().lastProductAddedId);
                        let color = lastAddedItem.options.find(o => o.label == "Color");
                        let size = lastAddedItem.options.find(o => o.label == "Size");
                        window.dataLayer = window.dataLayer || [];

                        dataLayer.push({
                            'event': 'addToCart-ftd',
                            'currencyCode': 'THB',
                            'ecommerce': {
                                'add': {
                                    'products': [
                                        {
                                            'id': lastAddedItem.product_sku,
                                            'name': lastAddedItem.product_name,
                                            'brand': lastAddedItem.brand,
                                            'price': lastAddedItem.product_price_value,
                                            'category': "<?php echo $_category; ?>",
                                            'variant': color === undefined ? "" : color.value,
                                            'dimension1': size === undefined ? "" : size.value,
                                            'quantity': amountAdded
                                        }
                                    ]
                                }
                            }
                        })
                    }
                }
            });
        });

    </script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "WeltPixel_ProductPage/js/sticky-addtocart": {}
        }
    }
</script>