<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\Sales\Block\Order\History $block */ ?>

<div class="order-back">
    <div class="actions-toolbar">
        <a class="action back" href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
    </div>
</div>
