<?php
/** @var  \WeltPixel\Newsletter\Helper\Data $_helper */
$_helper = $this->helper('WeltPixel\Newsletter\Helper\Data');
$proceedButtonLabel = $_helper->getExitIntentNewsletterSubmitButtonLabel();
$isCloseButtonEnabled = $_helper->isExitIntentNewsletterCloseButtonEnabled();
$closeButtonLabel = $_helper->getExitIntentNewsletterCloseButtonLabel();
?>
<form action="<?php echo $_helper->getFormActionUrl(); ?>"
      novalidate
      method="post"
      action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
      method="post"
      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
      id="weltpixel_exitintent">
    <div class="form-group">
        <input name="email" type="email" id="exitintent_newsletter_email"
               placeholder="<?php echo $block->escapeHtml(__('Enter your email address')) ?>"
               data-validate="{required:true, 'validate-email':true}"/>
        <button class="action subscribe primary wp-newsletter-button " title="<?= $block->escapeHtml($proceedButtonLabel) ?>" type="submit">
            <span><?= $block->escapeHtml($proceedButtonLabel) ?></span>
        </button>
        <?php if ($isCloseButtonEnabled) : ?>
            <button class="action primary wp-ei-close-popup wp-newsletter-button" title="<?= $block->escapeHtml($closeButtonLabel) ?>" type="button">
                <span><?= $block->escapeHtml($closeButtonLabel) ?></span>
            </button>
        <?php endif; ?>
        <?php if ($_helper->isExitIntentTermsConditionsEnabled()) : ?>
        <div class="terms-condition-container">
            <?php  if ($_helper->isExitIntentTermsConditionsCheckboxRequired()) : ?>
            <input id="exitintent_terms_conditions_consent" name="terms_conditions_consent" type="checkbox" data-validate="{required:true}" />
            <?php endif; ?>
            <label for="exitintent_terms_conditions_consent" ><?php echo $_helper->getExitIntentTermsConditionsText(); ?></label>
        </div>
        <?php endif; ?>
    </div>
</form>