<?php /**
* BSS Commerce Co.
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://bsscommerce.com/Bss-Commerce-License.txt
*
* @category  BSS
* @package   Bss_Popub
* @author    Extension Team
* @copyright Copyright (c) 2018-2020 BSS Commerce Co. ( http://bsscommerce.com )
* @license   http://bsscommerce.com/Bss-Commerce-License.txt
*/
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var Magento\Backend\Block\Template $block
 */
?>
<div class="popup-title"><?= $block->escapeHtml(__('Age Verification'))?></div>
<div class="popup-description"><?= $block->escapeHtml(__('You must be 18 in order to access this website. Are you 18 years of age or older?')); ?></div>
<button id="age_verification_yes"><?= $block->escapeHtml(__('Yes, I am 18')); ?></button>
<button id="age_verification_no"><?= $block->escapeHtml(__('No, Move to the page below')); ?></button>
<div  >
    <select id="age_verification_redirect">
        <option value="women.html"><?= $block->escapeHtml(__('Women')); ?></option>
        <option value="men.html"><?= $block->escapeHtml(__('Men')); ?></option>
        <option value=""><?= $block->escapeHtml("Home");  ?></option>
    </select>
</div>
