<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var  \Magento\Catalog\Block\Product\ProductList\Toolbar $block
 */
?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php if ($block->getTotalNum() == 1) :?>
    <span class="toolbar-number"><?= $block->escapeHtml(__('1 Item'))?></span>
    <?php else :?>
        <?= $block->escapeHtml(
            __('%1 Items', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'),
            ['span']
        ) ?>
    <?php endif; ?>
</p>
