<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Mega Menu Base for Magento 2
 */

use Magento\Framework\App\Action\Action;
use Amasty\MegaMenu\Block\Product\ProductsSlider;

// @codingStandardsIgnoreFile

/** @var ProductsSlider $block
 *  @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = $block->getBlockLayout();

    $image = ProductsSlider::AM_MEGA_MENU_IMAGES;
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    $widgetId = uniqid();
    $optionsState = $block->getProductOptionsState();
    ?>

    <div class="ammenu-product-list block widget -<?= /* @noEscape */ $mode ?>"
         data-ammenu-js='<?= /* @noEscape */ $block->getIdentifier() ?>'>
        <?php if ($block->getTitle()): ?>
            <p class="block-title">
                <?= $escaper->escapeHtml(__($block->getTitle())) ?>
            </p>
        <?php endif ?>

        <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>

        <div class="products-<?= /* @noEscape */ $mode ?> -<?= /* @noEscape */ $mode ?>">
            <ul class="product-items <?= /* @noEscape */ $type ?>"
                <?= ($mode === 'slider') ? (' data-ammenu-js="product-slider-' . $widgetId . '"') : '' ?>>

                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                    <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                    <div class="product-item-info">
                        <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>

                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $escaper->escapeHtml($_item->getName()) ?>"
                                   href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product-item-link">
                                    <?= $escaper->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>

                            <?php if ($templateType): ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($optionsState): ?>
                                <?= $block->getProductPriceHtml($_item, $type) ?>

                                <?= $block->getProductDetailsHtml($_item) ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                        <form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($_item->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>

                                                            <button type="submit"
                                                                    title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>"
                                                                    class="action tocart primary">
                                                                <?= /* @escapeNotVerified */ __('Add to Cart') ?>
                                                            </button>
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available">
                                                                <?= $escaper->escapeHtml(__('In stock')) ?>
                                                            </div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <?= $escaper->escapeHtml(__('Out of stock')) ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                           class="action towishlist"
                                                           data-action="add-to-wishlist"
                                                           title="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"></a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                        <a href="#"
                                                           class="action tocompare"
                                                           data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                           title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"></a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                <?php endif; ?>
                            <?php endif;?>
                        </div>
                    </div>
                    <?= /* @noEscape */ ($iterator == count($items) + 1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ul>
        </div>
        <?php if ($mode === 'slider'): ?>
            <script type="text/x-magento-init">
                {
                    "[data-ammenu-js='product-slider-<?= /* @noEscape */ $widgetId ?>']:not(.slick-initialized)": {
                        "ammenuProductSlider": {
                            "slidesToShow": "<?= $escaper->escapeJs($block->getSlidesToShow())?>",
                            "autoplay": "<?= $escaper->escapeJs($block->getAutoplayState()) ?>",
                            "autoplaySpeed": "<?= $escaper->escapeJs($block->getAutoplaySpeed())?>",
                            "width": <?= $escaper->escapeHtml($block->getSliderWidth()) ?>
                        }
                    }
                }
            </script>
        <?php endif;?>
        <?php if ($mode === 'grid'): ?>
            <?= $block->getPagerHtml() ?>

            <script type="text/x-magento-init">
                {
                    "[data-ammenu-js='<?= $block->getIdentifier() ?>']": {
                        "ammenuPager": {
                            "widget_data": <?= /* @noEscape */ json_encode([
                                'name' => $block->getNameInLayout(),
                                'data' => $block->getData(),
                                'identifier' => $block->getIdentifier()
                            ]); ?>
                        }
                    }
                }
            </script>
        <?php endif;?>
    </div>
    <script>
        require(['jquery'], function ($) {
            $('body').trigger('contentUpdated');
        });
    </script>
<?php endif;?>

