<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Improved Layered Navigation Base for Magento 2
 */
/** @var \Amasty\Shopby\Block\Navigation\Widget\Tooltip $block */
/** @var \Magento\Framework\Escaper $escaper */

$content = $block->getContent();
?>
<?php if ($content): ?>
    <script type="text/x-magento-init">
        {
            ".am-filter-items-<?= $escaper->escapeHtml($block->getFilterSetting()->getAttributeCode()) ?>": {
                "amShopbyFilterAddTooltip": {
                    "content": <?= /* @noEscape */ $block->jsonEncode($content) ?>,
                    "tooltipTemplate": <?= /* @noEscape */ $block->jsonEncode($block->getTooltipTemplate()) ?>
                }
            }
        }
    </script>
<?php endif; ?>
