<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Blog Pro for Magento 2
 */
/** @var $block \Magento\ReCaptchaUi\Block\ReCaptcha */
?>
<div
    class="field-recaptcha"
    id="<?= /* @noEscape */ $block->getRecaptchaId() ?>-container"
    data-bind="scope:'<?= /* @noEscape */ $block->getRecaptchaId() ?>'"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script>
    require(['jquery', 'domReady!'], function ($) {
        if ($('#subscribe-validate-detail').length) {
            $('#<?= /* @noEscape */ $block->getRecaptchaId() ?>-container')
                .appendTo('#subscribe-validate-detail');
        }
    });
</script>

<script type="text/x-magento-init">
{
    "#<?= /* @noEscape */ $block->getRecaptchaId() ?>-container": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
