<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Blog Pro for Magento 2
 */
/**
 * @var $block Magento\Backend\Block\Template
 * @var $escaper Magento\Framework\Escaper
 * @var $summaryViewModel Amasty\Blog\ViewModel\SummaryViewModel
 */

$summaryViewModel = $block->getViewModel();
?>
<div class="amblog-summary">
    <?= /** @noEscape  */ $summaryViewModel->getSummaryCmsBlockContent() ?>
</div>
