<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Blog Pro for Magento 2
 */
    /** @var \Amasty\Blog\Block\Amp\Head $block */
    $metaData = $block->getMetaData();
?>
<meta charset="utf-8">
<title><?= $block->escapeHtml($block->getTitle()) ?></title>
<link rel="canonical" href="<?= $block->escapeUrl($block->getCanonicalUrl()); ?>">
<link rel="icon" type="image/x-icon" href="<?= $block->escapeUrl($block->getFaviconUrl()); ?>">
<link rel="shortcut icon" type="image/x-icon" href="<?= $block->escapeUrl($block->getFaviconUrl()); ?>">
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "NewsArticle",
        "mainEntityOfPage": "http://cdn.ampproject.org/article-metadata.html",
        "headline": "<?= /* @noEscape */ $block->getTitle(); ?>",
        <?php if ($metaData): ?>
        "datePublished": "<?= /* @noEscape */ $metaData['published_at']; ?>",
        "dateModified": "<?= /* @noEscape */ $metaData['updated_at']; ?>",
        <?php endif; ?>
        "description": "<?= /* @noEscape */ $block->getMetaDescription(); ?>",
        <?php if (isset($metaData['posted_by'])): ?>
        "author": {
          "@type": "Person",
          "name": "<?= /* @noEscape */ $metaData['posted_by']; ?>"
        },
        "publisher": {
          "@type": "Organization",
          "name": "<?= /* @noEscape */ $metaData['posted_by']; ?>",
          "logo": {
            "@type": "ImageObject",
            "url": "<?= $block->escapeUrl($block->getLogoUrl()); ?>",
            "width": 600,
            "height": 60
          }
        },
        <?php endif; ?>
        "image": {
          "@type": "ImageObject",
          "url": "<?= $block->escapeUrl($block->getLogoUrl()); ?>",
          "height": 60,
          "width": 600
        }
  }
</script>

<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

<script async src="https://cdn.ampproject.org/v0.js"></script>
<script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
<script async custom-element="amp-social-share" src="https://cdn.ampproject.org/v0/amp-social-share-0.1.js"></script>
<script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
<script async custom-element="amp-selector" src="https://cdn.ampproject.org/v0/amp-selector-0.1.js"></script>
<script async custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js"></script>
<script async custom-element="amp-position-observer" src="https://cdn.ampproject.org/v0/amp-position-observer-0.1.js"></script>
<script async custom-element="amp-animation" src="https://cdn.ampproject.org/v0/amp-animation-0.1.js"></script>

<?= $block->getChildHtml() ?>
