<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Mega Menu Core Base for Magento 2
 */
/**
 * @var \Amasty\MegaMenuLite\Block\Container $block
 * @var \Magento\Framework\Escaper $escaper
 */

$item = $block->getData('item');
$class = $block->getData('class');
?>

<li class="category-item <?= $escaper->escapeHtmlAttr($class) ?>" role="presentation">
    <a href="<?= $escaper->escapeUrl($item['url']) ?>"
       tabindex="-1"
       title="<?= $escaper->escapeHtmlAttr($item['name']) ?>">
        <?= $escaper->escapeHtml($item['name']) ?>
    </a>
    <?php if (!empty($item['elems'])): ?>
        <ul class="submenu">
            <?php foreach ($item['elems'] as $key => $element): ?>
                <?= $block
                    ->setData('item', $element)
                    ->setData('class', $class . '-' . $key)
                    ->toHtml() ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</li>

