<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Mega Menu Core Base for Magento 2
 */
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<?php if (!empty($block->getItems())): ?>
<div class="ammenu-robots-navigation">
    <nav class="navigation" data-action="navigation" aria-disabled="true" aria-hidden="true" tabindex="-1">
        <ul aria-disabled="true" aria-hidden="true">
            <?php foreach ($block->getItems() as $key => $item): ?>
                <?= $block
                    ->getChildBlock('ammenu.robots.data.item')
                    ->setData('item', $item)
                    ->setData('class', 'nav-' . $key)
                    ->toHtml() ?>
            <?php endforeach; ?>
        </ul>
    </nav>
</div>
<?php endif; ?>
