<?php
/**
 * @var $block \PPGroup\NewsletterPopup\Block\NewsletterPopup
 */
?>
<div style="display: none">
    <div class="popup-newsletter">
        <div class="newsletter-subscribe">
            <h2><?php echo $block->getPopupTitle();?></h2>
            <?php echo $block->getPopupText();?>
            <?php echo $block->getChildHtml('newsletter-form'); ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".popup-newsletter": {
            "newsletterPopup": <?= /* @noEscape */ $block->getConfig(); ?>
        }
    }
</script>


