<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Product Feed for Magento 2
 */
/** @var \Magento\Backend\Block\Template $block */
?>
<div class="amfeed-preview" data-amfeed-js="preview-block">
    <p class="amfeed-preview message message-error error" data-amfeed-js="preview-error"></p>
    <textarea wrap="off" class="amfeed-preview content" data-amfeed-js="preview-content" readonly></textarea>
</div>