<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
    <?php
        $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
        ->init($_item->getOrderItem()->getProduct(), 'product_base_image')
        ->constrainOnly(TRUE)
        ->keepAspectRatio(TRUE)
        ->keepTransparency(TRUE)
        ->keepFrame(FALSE)
        ->resize(80, 80)->getUrl();
        ?>
        <img src="<?php echo $imageUrl; ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>" />
        <div class="product-name"><?= $block->escapeHtml($_item->getName()) ?></div>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option) : ?>
                <dt><?= $block->escapeHtml($option['label']) ?>:&nbsp;<?= /* @noEscape */  nl2br((string)$block->escapeHtml($option['value'])) ?></dt>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= (float) $_item->getQty() ?></td>
</tr>
