<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package GDPR Base for Magento 2
 */ /** @var \Magento\Backend\Block\Template $block*/ ?>
<h2 style="text-align: center;"><?= $block->escapeHtml(__('Kindly be informed that Active or Disabled Privacy Policy cannot be amended. '
        . 'Please use the CLONE function to create a new Privacy Policy version and amend the text.'));?></h2>
<br>
