<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package FAQ and Product Questions for Magento 2
 */
?>
<?=
/**
 * @var \Amasty\Faq\Block\View\Search $block
 */
$block->getChildHtml('amasty_faq_categories_search')
. $block->getChildHtml('amasty_faq_no_search_result')
. $block->getChildHtml('amasty_faq_questions')
. $block->getChildHtml('amasty_faq_ask_question_form');
