<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop by Brand for Magento 2
 */
?>
<li class="nav-item level0 level-top nav-item--parent classic nav-item--only-subcategories parent">
    <a href="<?= $block->escapeUrl($block->getAllBrandsUrl()) ?>" class="level-top">
        <span><?= $block->escapeHtml(__('Brands')) ?></span>
    </a>
</li>