<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Blog Pro for Magento 2
 */
/** @var \Amasty\Blog\Block\Sidebar\Category $block */

$treeHtml = $block->renderCategoriesTreeHtml();
?>

<?php if ($treeHtml): ?>
    <div class="amblog-categories sidebar-item">
        <div class="amblog-amp-title">
            <?= $block->escapeHtml($block->getBlockHeader()); ?>
        </div>
        <ul class="categories item level-<?= /* @noEscape */ $block->getDefaultLevel(); ?>">
            <?= /* @noEscape */ $treeHtml; ?>
        </ul>
    </div>
<?php endif; ?>
