<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Blog Pro for Magento 2
 */
/** @var \Amasty\Blog\Block\Sidebar\Search $block */
?>
<div class="amblog-search-wrap">
    <div class="amblog-amp-title">
        <?= $block->escapeHtml($block->getBlockHeader()); ?>
    </div>
    <div class="content">
        <form id="am_blog_search"
              action="<?= $block->escapeUrl($block->getAmpSearchUrl()) ?>"
              method="get"
              target="_top">
            <input type="text"
                   placeholder="<?= $block->escapeHtml($block->getBlockHeader()); ?>"
                   class="amblog-amp-input"
                   title="<?= $block->escapeHtml($block->getBlockHeader()); ?>"
                   id="search-blog"
                   name="query"
                   value="<?= $block->escapeHtml($block->getQuery()); ?>"
                   maxlength="100"/>
            <button class="amblog-amp-action" title="<?= $block->escapeHtml(__("Search")); ?>" type="submit">
                <?= $block->escapeHtml(__("Search")); ?>
            </button>
        </form>
    </div>
</div>
