<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Blog Pro for Magento 2
 */
/**
 * @var \Amasty\Blog\Block\Amp\Header $block
 */
// @codingStandardsIgnoreFile

$welcomeMessage = $block->getWelcome();
$fullName = $block->escapeHtml($block->getCustomerFullname());
?>
<?php switch ($block->getShowPart()) :
    case 'welcome': ?>
        <li class="greet welcome welcome-msg">
            <?php if ($fullName && $fullName !== ' ') : ?>
                <?= $block->escapeHtml(__('Welcome, %1!', $fullName)); ?>
            <?php else : ?>
                <span><?= /* @noEscape */ $welcomeMessage ?></span>
                <?= $block->getBlockHtml('header.additional') ?>
            <?php endif; ?>
        </li>
    <?php break; ?>
    <?php case 'other': ?>
        <?= $block->getChildHtml() ?>
    <?php break; ?>
<?php endswitch; ?>
